name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          # Shopify-webshop staat live, dus we recorden direct
          record: true
        env:
          # Deze sleutel heb je al ingesteld in je GitHub Secrets
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # GitHub heeft zijn eigen token nodig voor de actie
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}